wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    start_time: 1708643044.633894
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 15
      - 16
      - 23
      4: 3.7.7
      5: 0.13.11
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 8
data_root:
  desc: null
  value: data/processed/raw_corrected/Test
eval:
  desc: null
  value: true
name:
  desc: null
  value: eval_clean_data
